# Generated by Django 4.0.4 on 2022-06-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='giftcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftcard_id', models.IntegerField(default=0, unique=True)),
                ('user_id', models.IntegerField(default=0, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('m_time', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(default='DEFAULT VALUE', max_length=256)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('m_time', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'ordering': ['-c_time'],
            },
        ),
    ]
